In [1]:
import pandas as pd

In [4]:
hr = pd.read_csv('../data/raw/HR_Analytics.csv')

In [7]:
hr.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [8]:
hr.Department

0       Research & Development
1                        Sales
2                        Sales
3       Research & Development
4       Research & Development
                 ...
1475    Research & Development
1476                     Sales
1477                     Sales
1478                     Sales
1479    Research & Development
Name: Department, Length: 1480, dtype: object

In [10]:
hr['Department']

0       Research & Development
1                        Sales
2                        Sales
3       Research & Development
4       Research & Development
                 ...
1475    Research & Development
1476                     Sales
1477                     Sales
1478                     Sales
1479    Research & Development
Name: Department, Length: 1480, dtype: object

In [11]:
hr['EducationField'][0]

'Life Sciences'

In [12]:
hr.iloc[0]

EmpID                                        RM297
Age                                             18
AgeGroup                                     18-25
Attrition                                      Yes
BusinessTravel                       Travel_Rarely
DailyRate                                      230
Department                  Research & Development
DistanceFromHome                                 3
Education                                        3
EducationField                       Life Sciences
EmployeeCount                                    1
EmployeeNumber                                 405
EnvironmentSatisfaction                          3
Gender                                        Male
HourlyRate                                      54
JobInvolvement                                   3
JobLevel                                         1
JobRole                      Laboratory Technician
JobSatisfaction                                  3
MaritalStatus                               Single
MonthlyIncome                                 1420
SalarySlab                                 Upto 5k
MonthlyRate                                  25233
NumCompaniesWorked                               1
Over18                                           Y
OverTime                                        No
PercentSalaryHike                               13
PerformanceRating                                3
RelationshipSatisfaction                         3
StandardHours                                   80
StockOptionLevel                                 0
TotalWorkingYears                                0
TrainingTimesLastYear                            2
WorkLifeBalance                                  3
YearsAtCompany                                   0
YearsInCurrentRole                               0
YearsSinceLastPromotion                          0
YearsWithCurrManager                           0.0
Name: 0, dtype: object

In [16]:
hr.iloc[:5, 0:7]

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development
1,RM302,18,18-25,No,Travel_Rarely,812,Sales
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales
3,RM728,18,18-25,No,Non-Travel,287,Research & Development
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development

In [19]:
hr.loc[:5, 'Department']

0    Research & Development
1                     Sales
2                     Sales
3    Research & Development
4    Research & Development
5    Research & Development
Name: Department, dtype: object

In [20]:
hr.loc[:5, ['Department', 'EducationField']]

               Department EducationField
0  Research & Development  Life Sciences
1                   Sales        Medical
2                   Sales      Marketing
3  Research & Development  Life Sciences
4  Research & Development        Medical
5  Research & Development  Life Sciences

In [21]:
hr.set_index('EmployeeNumber')

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
EmployeeNumber,,,,,,,,,,,,,,,,,,,,,
405,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
411,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
614,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
1012,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
1156,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,4,80,0,33,5,1,29,8,11,10.0
573,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0
732,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,4,80,0,10,1,3,2,2,2,2.0
1233,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,2,80,1,12,3,3,11,7,1,9.0
1697,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [23]:
hr['EducationField'] == 'Medical'

0       False
1        True
2       False
3       False
4        True
        ...
1475    False
1476    False
1477    False
1478    False
1479     True
Name: EducationField, Length: 1480, dtype: bool

In [24]:
hr.loc[hr.EducationField == 'Medical']

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
6,RM1154,18,18-25,Yes,Travel_Frequently,544,Sales,3,2,Medical,...,3,80,0,0,2,4,0,0,0,0.0
7,RM1312,18,18-25,No,Non-Travel,1431,Research & Development,14,3,Medical,...,3,80,0,0,4,1,0,0,0,0.0
9,RM150,19,18-25,No,Travel_Rarely,1181,Research & Development,3,1,Medical,...,4,80,0,1,3,3,1,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1462,RM1302,58,55+,No,Non-Travel,350,Sales,2,3,Medical,...,4,80,1,37,0,2,16,9,14,14.0
1465,RM007,59,55+,No,Travel_Rarely,1324,Research & Development,3,3,Medical,...,1,80,3,12,3,2,1,0,0,NaN
1470,RM233,59,55+,No,Travel_Rarely,818,Human Resources,6,2,Medical,...,4,80,0,7,2,2,2,2,2,2.0
1474,RM920,59,55+,No,Travel_Rarely,1429,Research & Development,18,4,Medical,...,4,80,0,25,6,2,9,7,5,4.0
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [25]:
hr.loc[(hr.EducationField == 'Medical') & (hr.Age > 30)]

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
391,RM073,31,26-35,No,Travel_Rarely,1082,Research & Development,1,4,Medical,...,2,80,0,1,4,3,1,1,1,NaN
395,RM181,31,26-35,No,Travel_Rarely,140,Research & Development,12,1,Medical,...,3,80,1,7,0,3,4,2,0,2.0
396,RM225,31,26-35,No,Non-Travel,979,Research & Development,1,4,Medical,...,4,80,1,6,2,3,5,4,1,4.0
397,RM246,31,26-35,No,Travel_Frequently,1327,Research & Development,3,4,Medical,...,1,80,1,9,3,3,2,2,2,2.0
398,RM260,31,26-35,Yes,Travel_Frequently,307,Research & Development,29,2,Medical,...,2,80,0,6,2,4,5,4,1,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1462,RM1302,58,55+,No,Non-Travel,350,Sales,2,3,Medical,...,4,80,1,37,0,2,16,9,14,14.0
1465,RM007,59,55+,No,Travel_Rarely,1324,Research & Development,3,3,Medical,...,1,80,3,12,3,2,1,0,0,NaN
1470,RM233,59,55+,No,Travel_Rarely,818,Human Resources,6,2,Medical,...,4,80,0,7,2,2,2,2,2,2.0
1474,RM920,59,55+,No,Travel_Rarely,1429,Research & Development,18,4,Medical,...,4,80,0,25,6,2,9,7,5,4.0
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [26]:
hr.loc[(hr.EducationField == 'Medical') | (hr.Age > 30)]

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
6,RM1154,18,18-25,Yes,Travel_Frequently,544,Sales,3,2,Medical,...,3,80,0,0,2,4,0,0,0,0.0
7,RM1312,18,18-25,No,Non-Travel,1431,Research & Development,14,3,Medical,...,3,80,0,0,4,1,0,0,0,0.0
9,RM150,19,18-25,No,Travel_Rarely,1181,Research & Development,3,1,Medical,...,4,80,0,1,3,3,1,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,4,80,0,33,5,1,29,8,11,10.0
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,4,80,0,10,1,3,2,2,2,2.0
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,2,80,1,12,3,3,11,7,1,9.0
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [27]:
hr.loc[hr.BusinessTravel.isin(['Non-Travel', 'Travel_Frequently'])]

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
5,RM973,18,18-25,No,Non-Travel,1124,Research & Development,1,3,Life Sciences,...,3,80,0,0,5,4,0,0,0,0.0
6,RM1154,18,18-25,Yes,Travel_Frequently,544,Sales,3,2,Medical,...,3,80,0,0,2,4,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1462,RM1302,58,55+,No,Non-Travel,350,Sales,2,3,Medical,...,4,80,1,37,0,2,16,9,14,14.0
1463,RM1311,58,55+,No,Travel_Frequently,1216,Research & Development,15,4,Life Sciences,...,2,80,0,23,3,3,2,2,2,2.0
1467,RM071,59,55+,No,Travel_Frequently,1225,Sales,1,1,Life Sciences,...,4,80,0,20,2,2,4,3,1,NaN
1468,RM106,59,55+,No,Non-Travel,1420,Human Resources,2,4,Human Resources,...,4,80,1,30,3,3,3,2,2,2.0
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0

In [30]:
hr.loc[hr.YearsInCurrentRole.notnull()]

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,4,80,0,33,5,1,29,8,11,10.0
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,4,80,0,10,1,3,2,2,2,2.0
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,2,80,1,12,3,3,11,7,1,9.0
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [31]:
hr['Department'] ==   'Sales'
hr['Department']

0       Research & Development
1                        Sales
2                        Sales
3       Research & Development
4       Research & Development
                 ...
1475    Research & Development
1476                     Sales
1477                     Sales
1478                     Sales
1479    Research & Development
Name: Department, Length: 1480, dtype: object

In [32]:
hr.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [34]:
dep = hr['Department']
dep

0       Research & Development
1                        Sales
2                        Sales
3       Research & Development
4       Research & Development
                 ...
1475    Research & Development
1476                     Sales
1477                     Sales
1478                     Sales
1479    Research & Development
Name: Department, Length: 1480, dtype: object

In [40]:
type(dep)

pandas.core.series.Series

In [42]:
first_EducationField = hr.loc[0, 'EducationField']
first_EducationField

'Life Sciences'

In [44]:
first_row = hr.loc[0, :]
first_row

EmpID                                        RM297
Age                                             18
AgeGroup                                     18-25
Attrition                                      Yes
BusinessTravel                       Travel_Rarely
DailyRate                                      230
Department                  Research & Development
DistanceFromHome                                 3
Education                                        3
EducationField                       Life Sciences
EmployeeCount                                    1
EmployeeNumber                                 405
EnvironmentSatisfaction                          3
Gender                                        Male
HourlyRate                                      54
JobInvolvement                                   3
JobLevel                                         1
JobRole                      Laboratory Technician
JobSatisfaction                                  3
MaritalStatus                               Single
MonthlyIncome                                 1420
SalarySlab                                 Upto 5k
MonthlyRate                                  25233
NumCompaniesWorked                               1
Over18                                           Y
OverTime                                        No
PercentSalaryHike                               13
PerformanceRating                                3
RelationshipSatisfaction                         3
StandardHours                                   80
StockOptionLevel                                 0
TotalWorkingYears                                0
TrainingTimesLastYear                            2
WorkLifeBalance                                  3
YearsAtCompany                                   0
YearsInCurrentRole                               0
YearsSinceLastPromotion                          0
YearsWithCurrManager                           0.0
Name: 0, dtype: object

In [54]:
first_EducationField = hr.EducationField.iloc[:10]
first_EducationField

0    Life Sciences
1          Medical
2        Marketing
3    Life Sciences
4          Medical
5    Life Sciences
6          Medical
7          Medical
8        Marketing
9          Medical
Name: EducationField, dtype: object

In [56]:
indexed = hr.loc[[1,4,6,8,9]]
indexed

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
6,RM1154,18,18-25,Yes,Travel_Frequently,544,Sales,3,2,Medical,...,3,80,0,0,2,4,0,0,0,0.0
8,RM128,19,18-25,Yes,Travel_Rarely,528,Sales,22,1,Marketing,...,4,80,0,0,2,2,0,0,0,0.0
9,RM150,19,18-25,No,Travel_Rarely,1181,Research & Development,3,1,Medical,...,4,80,0,1,3,3,1,0,0,0.0

In [58]:
columns = ['EmployeeNumber', 'Department', 'EducationField']
indices = [0, 1, 10, 100]
df = hr.loc[indices, columns]
df

     EmployeeNumber              Department    EducationField
0               405  Research & Development     Life Sciences
1               411                   Sales           Medical
10              235                   Sales  Technical Degree
100             350  Research & Development     Life Sciences

In [61]:
df = hr.loc[:99, ['EmployeeNumber', 'Department', 'EducationField']]
df

    EmployeeNumber              Department EducationField
0              405  Research & Development  Life Sciences
1              411                   Sales        Medical
2              614                   Sales      Marketing
3             1012  Research & Development  Life Sciences
4             1156  Research & Development        Medical
..             ...                     ...            ...
95            1746         Human Resources        Medical
96            1981  Research & Development  Life Sciences
97             142                   Sales      Marketing
98             143  Research & Development        Medical
99             183                   Sales  Life Sciences

[100 rows x 3 columns]

In [64]:
Non_T = hr.loc[hr['BusinessTravel'] == 'Non-Travel']
Non_T

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
5,RM973,18,18-25,No,Non-Travel,1124,Research & Development,1,3,Life Sciences,...,3,80,0,0,5,4,0,0,0,0.0
7,RM1312,18,18-25,No,Non-Travel,1431,Research & Development,14,3,Medical,...,3,80,0,0,4,1,0,0,0,0.0
15,RM893,19,18-25,Yes,Non-Travel,504,Research & Development,10,3,Medical,...,2,80,0,1,2,4,1,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1423,RM915,55,46-55,No,Non-Travel,177,Research & Development,8,1,Medical,...,4,80,1,34,3,3,33,9,15,0.0
1445,RM1442,56,55+,No,Non-Travel,667,Research & Development,1,4,Life Sciences,...,1,80,1,13,2,2,13,12,1,9.0
1454,RM309,58,55+,No,Non-Travel,390,Research & Development,1,4,Life Sciences,...,4,80,1,12,2,3,5,3,1,2.0
1462,RM1302,58,55+,No,Non-Travel,350,Sales,2,3,Medical,...,4,80,1,37,0,2,16,9,14,14.0
1468,RM106,59,55+,No,Non-Travel,1420,Human Resources,2,4,Human Resources,...,4,80,1,30,3,3,3,2,2,2.0