In [1]:
import pandas as pd

In [2]:
reviews = pd.read_csv('../data/raw/kaggle_pandas.csv')

In [4]:
reviews.head(3)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm

### 1. What is the data type of the points column in the dataset?

In [6]:
reviews.points.dtype

dtype('int64')

### 2. Create a Series from entries in the points column, but convert the entries to strings. Hint: strings are str in native Python.

In [11]:
reviews.points.astype('str')

0         87
1         87
2         87
3         87
4         87
          ..
129966    90
129967    90
129968    90
129969    90
129970    90
Name: points, Length: 129971, dtype: object

### 3. Sometimes the price column is null. How many reviews in the dataset are missing a price?

In [17]:
reviews.price.isnull().sum()

np.int64(8996)

### 4. What are the most common wine-producing regions? Create a Series counting the number of times each value occurs in the region_1 field. This field is often missing data, so replace missing values with Unknown. Sort in descending order. Your output should look something like this:

* Unknown                    21247
* Napa Valley                 4480
*                            ...  
* Bardolino Superiore            1
* Primitivo del Tarantino        1
* Name: region_1, Length: 1230, dtype: int64

In [20]:
reviews.region_1.fillna('Unknown').value_counts().sort_values(ascending = False)

region_1
Unknown                 21247
Napa Valley              4480
Columbia Valley (WA)     4124
Russian River Valley     3091
California               2629
                        ...
Offida Rosso                1
Corton Perrières            1
Isle St. George             1
Geelong                     1
Paestum                     1
Name: count, Length: 1230, dtype: int64

#### practice

In [38]:
reviews.head(2)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos

In [26]:
reviews.region_1.head(10)

0                   Etna
1                    NaN
2      Willamette Valley
3    Lake Michigan Shore
4      Willamette Valley
5                Navarra
6               Vittoria
7                 Alsace
8                    NaN
9                 Alsace
Name: region_1, dtype: object

In [ ]:
reviews.region_1.dropna().head(10)

0                    Etna
2       Willamette Valley
3     Lake Michigan Shore
4       Willamette Valley
5                 Navarra
6                Vittoria
7                  Alsace
9                  Alsace
10            Napa Valley
11                 Alsace
Name: region_1, dtype: object

In [28]:
reviews.region_1.isna().head(10)

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8     True
9    False
Name: region_1, dtype: bool

In [29]:
reviews.region_1.isnull().head(10)

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8     True
9    False
Name: region_1, dtype: bool

In [42]:

reviews.drop_duplicates( subset = ['country'],ignore_index = True).shape

(44, 14)

In [35]:
reviews.shape

(129971, 14)

In [36]:
reviews.drop_duplicates().shape

(129971, 14)