# 1. Pandas Series

### Creating Series

In [152]:
import numpy as np 
import pandas as pd

In [153]:
lables = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [154]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [155]:
pd.Series(my_list,index = lables)

a    10
b    20
c    30
dtype: int64

In [156]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [157]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# 2. DataFrames

#### Creating DataFrame

In [158]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
}
df = pd.DataFrame(data)
df

    Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   42    London

In [159]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [160]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

#### Creating a New Column

In [161]:
df2['Designation'] = ['Dotcor','Eng,','Doctor','Eng.']

In [162]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Dotcor
1   Anna   34     Paris   70000        Eng,
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

#### Remove a Column

In [163]:
df2.drop('Designation',axis = 1,inplace= True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [164]:
df2.drop(["City","Salary"],axis = 1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [165]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

#### Selecting Rows

In [166]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [167]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

#### Selecting Subsets of Rows and Columns

In [168]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

#### Conditional Selection

In [169]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [170]:
# i only see those people whose age is above 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [171]:
# I want to these people whose age is above 30 and city most be paris
df2[(df2['Age'] > 30 ) & (df2['City']=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# Missing Data

#### Finding missing data

In [172]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

In [173]:
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [174]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [175]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [176]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

#### Remove missing Value

In [177]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [178]:
df.dropna(thresh = 3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

#### Filling the missing data

In [179]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [180]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [181]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# 4. Merging Joining Concatination

##### Merging 2 dataframs

In [182]:

employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [183]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [184]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [185]:
pd.merge(employees,salaries,on = 'employee_id',how = 'inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [186]:
pd.merge(employees,salaries,on = 'employee_id',how = 'outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [187]:
pd.merge(employees,salaries,on = 'employee_id',how = 'left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [188]:
pd.merge(employees,salaries,on = 'employee_id',how = 'right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

##### Concatination 2 dataframes

In [189]:

df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [190]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [191]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [192]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [193]:
pd.concat([df1,df2],axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**joining 2 dataFrames**

In [194]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [195]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [196]:
df2

   score
2     85
3     90
4     75

In [197]:
df1.join(df2,how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

# 5. Groupby Aggregation

In [198]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [199]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [200]:
# Group by Category and calculate the sum of 
cat = df.groupby("Category")['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [201]:
# Group by Store and calculate the sum of Sales
s = df.groupby('Store')['Sales'].sum()
s

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [202]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**Agrregation**

In [203]:
df['Sales'].mean()

np.float64(187.5)

In [204]:
df['Sales'].agg(['min','max','mean','std','median','count'])

min       100.000000
max       300.000000
mean      187.500000
std        66.062741
median    190.000000
count       8.000000
Name: Sales, dtype: float64

# 6. Pivot Tables

In [205]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

In [206]:
df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    442     56   John
1  2023-01-02       B   West    791     80   Mary
2  2023-01-03       C  North    522     71    Bob
3  2023-01-04       D  South    256     65  Alice
4  2023-01-05       A   East    693     71   John
5  2023-01-06       B   West    296     59   Mary
6  2023-01-07       C  North    381     59    Bob
7  2023-01-08       D  South    746     46  Alice
8  2023-01-09       A   East    294     84   John
9  2023-01-10       B   West    563     19   Mary
10 2023-01-11       C  North    124     20    Bob
11 2023-01-12       D  South    839     16  Alice
12 2023-01-13       A   East    543     53   John
13 2023-01-14       B   West    119     15   Mary
14 2023-01-15       C  North    980     25    Bob
15 2023-01-16       D  South    631     78  Alice
16 2023-01-17       A   East    724     31   John
17 2023-01-18       B   West    119     27   Mary
18 2023-01-19       C  North    874     84    Bob
19 2023-01-20       D  South    278     53  Alice

In [207]:
pd.pivot_table(df,values= 'Sales',index= 'Region',columns= 'Product',aggfunc='median')

Product      A      B      C      D
Region
East     543.0    NaN    NaN    NaN
North      NaN    NaN  522.0    NaN
South      NaN    NaN    NaN  631.0
West       NaN  296.0    NaN    NaN

In [208]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     539.2    NaN    NaN    NaN  59.0   NaN   NaN   NaN
North      NaN    NaN  576.2    NaN   NaN   NaN  51.8   NaN
South      NaN    NaN    NaN  550.0   NaN   NaN   NaN  51.6
West       NaN  377.6    NaN    NaN   NaN  40.0   NaN   NaN

**Cross Tabs**

In [209]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# 7. Operations

##### Dataframe Basic Operations

In [210]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [211]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [212]:
df1.shape

(5, 3)

In [213]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [214]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [215]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

**DataFrames Applying Functions**

In [216]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [217]:
def squre(x):
    return x**2

In [218]:
df1['D'] = df1['B'].apply(squre)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500