# Day 3: Filtering, Boolean Logic & Sorting

## Objective

Practice filtering, Boolean logic, sorting, `.map()`, and `.apply()` using the HR Analytics dataset.

## Topics

- Boolean conditions
- `&` and `|`
- Conditional filtering
- `.sort_values()`
- `.map()`
- `.apply()`
- Business-oriented filtering

In [42]:
import pandas as pd
import numpy as np

In [43]:
df = pd.read_csv('../data/raw/Hr_Analytics.csv')

In [44]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [45]:
df.DailyRate.describe()

count    1480.000000
mean      801.384459
std       403.126988
min       102.000000
25%       465.000000
50%       800.000000
75%      1157.000000
max      1499.000000
Name: DailyRate, dtype: float64

In [46]:
df.EducationField.describe()

count              1480
unique                6
top       Life Sciences
freq                607
Name: EducationField, dtype: object

In [47]:
df.Age.mean()

np.float64(36.917567567567566)

In [48]:
df.EmpID.unique()

array(['RM297', 'RM302', 'RM458', ..., 'RM537', 'RM880', 'RM1210'],
      shape=(1470,), dtype=object)

In [49]:
df.BusinessTravel.value_counts()

BusinessTravel
Travel_Rarely        1042
Travel_Frequently     279
Non-Travel            151
TravelRarely            8
Name: count, dtype: int64

In [50]:
df_age_mean = df.Age.mean()
df.Age.map(lambda a: a - df_age_mean)

0      -18.917568
1      -18.917568
2      -18.917568
3      -18.917568
4      -18.917568
          ...
1475    23.082432
1476    23.082432
1477    23.082432
1478    23.082432
1479    23.082432
Name: Age, Length: 1480, dtype: float64

In [51]:
def remean_points(row):
    row.Age = row.Age - df_age_mean
    return row

df.apply(remean_points, axis='columns')

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,-18.917568,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,-18.917568,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,-18.917568,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,-18.917568,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,-18.917568,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,23.082432,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,4,80,0,33,5,1,29,8,11,10.0
1476,RM428,23.082432,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0
1477,RM537,23.082432,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,4,80,0,10,1,3,2,2,2,2.0
1478,RM880,23.082432,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,2,80,1,12,3,3,11,7,1,9.0
1479,RM1210,23.082432,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [52]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [53]:
df_age_mean = df.Age.mean()
df.Age - df_age_mean

0      -18.917568
1      -18.917568
2      -18.917568
3      -18.917568
4      -18.917568
          ...
1475    23.082432
1476    23.082432
1477    23.082432
1478    23.082432
1479    23.082432
Name: Age, Length: 1480, dtype: float64

In [54]:
df.Department + ' - ' + df.BusinessTravel

0       Research & Development - Travel_Rarely
1                        Sales - Travel_Rarely
2                    Sales - Travel_Frequently
3          Research & Development - Non-Travel
4          Research & Development - Non-Travel
                         ...
1475    Research & Development - Travel_Rarely
1476                 Sales - Travel_Frequently
1477                     Sales - Travel_Rarely
1478                     Sales - Travel_Rarely
1479    Research & Development - Travel_Rarely
Length: 1480, dtype: object

In [55]:
hrdf = df

In [56]:
hrdf.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [57]:
hr_median_age = hrdf.Age.median()
hr_median_age

36.0

In [58]:
Departments = df.Department.unique()
Departments

array(['Research & Development', 'Sales', 'Human Resources'], dtype=object)

In [59]:
hrdf.Department.value_counts()

Department
Research & Development    967
Sales                     450
Human Resources            63
Name: count, dtype: int64

In [60]:
centered_age = hrdf.Age - hrdf.Age.mean()
centered_age

0      -18.917568
1      -18.917568
2      -18.917568
3      -18.917568
4      -18.917568
          ...
1475    23.082432
1476    23.082432
1477    23.082432
1478    23.082432
1479    23.082432
Name: Age, Length: 1480, dtype: float64